---
title: "Data Description and Check - Cytokine"
author: "Joe Hou, Yunda Huang, James Kobie"
date: "2024-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hrbrthemes)
library(GGally)
library(viridis)
library(dplyr)
library(tidyverse)
library(corrplot)
library(RColorBrewer)
library(funkyheatmap)
library(clusterProfiler)
library(xlsx)
load("../RawData/Subject_Specimen_info.Rdata")
```

<div style="font-size:20px;">
  Here's the data check and description on cytokines (from serum assay) data over 2020, 2021 and 2022 dataset. 
</div>

# <span style="font-size:24px;"> Data loading and processing </span>

```{r}
# load data, cytokine
cytokine_2020 = read.csv("../RawData/Training/2020/2020LD_plasma_cytokine_concentration.tsv", sep = "\t")
cytokine_2021 = read.csv("../RawData/Training/2021/2021LD_plasma_cytokine_concentration.tsv", sep = "\t")
cytokine_2022 = read.csv("../RawData/Prediction/2022BD_plasma_cytokine_concentration.tsv", sep = "\t")
```

# <span style="font-size:24px;">Cell Frequency variables availability across 2020, 2021 and 2022 dataset </span>

```{r overlap figure, warning=FALSE, message=FALSE}
# check overlap
overlap_check = data.frame(matrix(NA, ncol = 5, nrow = 45))
colnames(overlap_check) = c("UNIPROT", "Protein","Y2020", "Y2021", "Y2022")
overlap_check$UNIPROT = unique(cytokine_2021$protein_id)
overlap_check[overlap_check$UNIPROT  %in% unique(cytokine_2020$protein_id),3] = 1
overlap_check[overlap_check$UNIPROT  %in% unique(cytokine_2021$protein_id),4] = 1
overlap_check[overlap_check$UNIPROT  %in% unique(cytokine_2022$protein_id),5] = 1
overlap_check[is.na(overlap_check)] = 0

overlap_check = overlap_check %>%
  mutate(UNIPROT_first_part = sapply(strsplit(UNIPROT, "_"), "[", 1))

# convert UNIPROT to Gene Symbol
Protein_IDs = bitr(overlap_check$UNIPROT_first_part, fromType="UNIPROT" , toType="SYMBOL", OrgDb="org.Hs.eg.db") 
Protein_names = distinct(Protein_IDs, UNIPROT, .keep_all = TRUE) 
write.csv(Protein_names, file = "Protein_names.csv", row.names = FALSE)

for (i in 1:nrow(Protein_names)) {
  if (Protein_names$UNIPROT[i] == overlap_check$UNIPROT_first_part[i]) {
    overlap_check$Protein[i] = Protein_names$SYMBOL[i]
  }
}

overlap_check = overlap_check %>% arrange(desc(rowSums(dplyr::select(., Y2020, Y2021, Y2022) == 1)),
                                          desc(Y2020),
                                          desc(Y2021),
                                          desc(Y2022))
```

```{r, echo=FALSE, fig.width=10, fig.height=12, warning=FALSE, message=FALSE}
# plot cell type overlap over years
column_info = tribble(
  ~id,         ~group,      ~name,    ~geom,            ~palette,           ~options,
  "UNIPROT",      "",       "",       "text",           NA,                  list(hjust = 1, width = 5),
  "Protein",      "",       "",       "text",           NA,                  list(hjust = 1, width = 4),
  "Y2020",       "",       "Y2020",     "funkyrect",     "palette1",          list(),
  "Y2021",       "",       "Y2021",     "funkyrect",     "palette1",          list(),
  "Y2022",       "",       "Y2022",     "funkyrect",     "palette1",          list())

funky_heatmap(overlap_check, column_info = column_info, scale_column = FALSE, 
              palettes =  list(palette1 = "black"), 
              expand = list(xmax = 1), col_annot_angle = 90)
```

# <span style="font-size:24px;">Check main variables across dataset </span>

```{r}
# clean up and sort out
cytokine_2020_sel = cytokine_2020 %>% 
  left_join(select(Specimen_2020_sel, all_of(c("specimen_id", "subject_id", "dataset", "day_plot"))), by = "specimen_id") %>%
  left_join(select(Subject_2020, all_of(c("subject_id", "infancy_vac"))), by = "subject_id")

cytokine_2021_sel = cytokine_2021 %>% 
  left_join(select(Specimen_2021_sel, all_of(c("specimen_id", "subject_id", "dataset", "day_plot"))), by = "specimen_id") %>%
  left_join(select(Subject_2021, all_of(c("subject_id", "infancy_vac"))), by = "subject_id")

# combine two datasets
cytokine_dataset_combine = rbind(cytokine_2020_sel, cytokine_2021_sel) %>% 
  filter(day_plot %in% c(0, 1, 3, 7, 14)) %>% 
  select(all_of(c("protein_id", "protein_expression", "day_plot", "subject_id", "infancy_vac", "dataset"))) %>%
  mutate(Day = factor(paste0("Day", day_plot), levels = c("Day0", "Day1", "Day3", "Day7", "Day14"))) %>%
  unite(vac_yr, c("infancy_vac", "dataset")) %>%
  mutate(vac_yr = factor(vac_yr, levels = c("aP_2020", "wP_2020", "aP_2021", "wP_2021")))
```

```{r, echo=FALSE, fig.width=16, fig.height=6, warning=FALSE, message=FALSE}
cytokine_dataset_combine %>%
  filter(protein_id %in% c("P05231", "P22301", "P10145", "P80098", "P13232", "P10147", "P35225")) %>%
  mutate(protein_id = factor(protein_id, levels = c("P05231", "P22301", "P10145", "P80098", "P13232", "P10147", "P35225"))) %>%
  ggplot(aes(x = Day , y = protein_expression, group = subject_id, color = vac_yr)) +
  geom_line() +
  geom_point(aes()) +
  scale_x_discrete(expand = c(0.03,0.03)) + 
  ylab("Protein expression") +
  ggh4x::facet_wrap2( ~ protein_id, scales = "free_y", ncol = 4) + 
  scale_color_manual(values=c("aP_2020" = "#DB4437", "wP_2020" = "#0F9D58",  
                              "aP_2021"=  "#F4B400", "wP_2021"= "#4285F4")) + 
  theme_bw()+
  theme(panel.background = element_rect( color = "black"),
               panel.grid.major = element_line(color = "gray"),
               panel.grid.minor = element_line(color = "gray"),
               strip.text = element_text(size = 16),
               plot.title = element_text(size = 16),
               axis.text.x  = element_text(size = 14),
               axis.text.y  = element_text(size = 14),
               axis.title.x = element_blank(),
               axis.title.y = element_text(size = 14),
               legend.title = element_text(size = 14),
               legend.text = element_text(size = 14))
```