---
title: "Prediction on CCL3 Day3/Day0"
author: "Joe Hou, Yunda Huang, James Kobie"
date: "2024-01-13"
output: html_document
---

<div style="font-size:20px;">
For the specific goal of predicting CCL3 Fold change Day 3/Day 0, we have chosen to use RNAseq, BTM scores and Ab data from the 2020 and 2021 dataset. 
</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SuperLearner)
library(caret)
library(dplyr)
library(xlsx)
load("../ProcessedData/Ab_data_selection.Rdata")
load("../ProcessedData/RNA_data_selection.Rdata")
load("../ProcessedData/Prediction2022_All_Day0.Rdata")
load("../ProcessedData/Subject_Specimen_info.Rdata")
source("../Markdown/SuperLearnerMethod.R")
```


```{r, warning=FALSE, message=FALSE}
sl.library = list("SL.mean",
                  "SL.glmnet.ridge",
                  "SL.glmnet.25",
                  "SL.glmnet.50",
                  "SL.glmnet.75",
                  "SL.glmnet.lasso",
                  "SL.biglasso", 
                  "SL.ranger.imp",
                  "SL.ranger.reg",
                  "SL.ranger.small",
                  "SL.ranger.large")

#------------------------------------------------------------------------------#
# 4. training on RNA dataset (top2000 gene and 345 BTMs) + Ab 
#------------------------------------------------------------------------------#
Subject_meta = rbind(Subject_2020, Subject_2021)

# Ab data
Ab_common_cols = intersect(colnames(Ab_2020_D0_D14_log_norm_merge), 
                           colnames(Ab_2021_D0_D14_log_norm_merge))

Ab.input_data = bind_rows(dplyr::select(Ab_2020_D0_D14_log_norm_merge, Ab_common_cols), 
                          dplyr::select(Ab_2021_D0_D14_log_norm_merge, Ab_common_cols)) %>%
  dplyr::select(-c(Age, gender_numeric, infancy_vac_numeric, infancy_vac, Gender, target_D14_PTIgG)) 

# remove one row that contain NA
Ab_rows_with_na = apply(Ab.input_data , 1, function(x) any(is.na(x)))
Ab.input_data  = Ab.input_data [!Ab_rows_with_na, ]

# RNA data
RNA.BTM.FC.input_data = RNA_Day0_norm_top2000_Day3_CCL3 %>%
  dplyr::select(-c(target_D3_CCL3)) %>%
  left_join(Subject_meta %>% 
              mutate(subject_id = as.character(subject_id)) %>% 
              dplyr::select(all_of(c("subject_id", "infancy_vac", "biological_sex", "age_at_boost"))), by = "subject_id") %>%
  left_join(BTM_Day0_Day3_CCL3 %>%
              mutate(subject_id = as.character(subject_id)) %>%
              dplyr::select(-c(target_D3_CCL3)), by = "subject_id") %>%
  mutate(gender_numeric = ifelse(biological_sex == "Female", 0, 1)) %>%
  mutate(infancy_vac_numeric = ifelse(infancy_vac == "aP", 0, 1)) %>%
  dplyr::rename(Age = age_at_boost) %>%
  left_join(RNA_D0_D3_CCL3_FC %>%
              mutate(subject_id = as.character(subject_id)) %>% 
              dplyr::select(all_of(c("subject_id", "D3_D0_FC_CCL3_log_norm"))), by = "subject_id") %>%
  dplyr::select(-c(infancy_vac, biological_sex))

# select subjects from Ab and RNA
ids_ab = unique(Ab.input_data$subject_id); length(ids_ab)
ids_rna = unique(RNA.BTM.FC.input_data$subject_id); length(ids_rna)
sel_subject = intersect(ids_ab, ids_rna)

# select Ab and RNA data
Ab.RNA.BTM.FC.input_data = Ab.input_data %>%
  mutate(subject_id = as.character(subject_id)) %>%
  filter(subject_id %in% sel_subject) %>%
  left_join(RNA.BTM.FC.input_data %>%
              filter(subject_id %in% sel_subject), by = "subject_id") %>%
  dplyr::select(-c(subject_id)) %>%
  dplyr::mutate_if(is.numeric, round, digits = 2)

# remove one row that contain NA
Ab.RNA.BTM.rows_with_na = apply(Ab.RNA.BTM.FC.input_data, 1, function(x) any(is.na(x)))
Ab.RNA.BTM.FC.input_data = Ab.RNA.BTM.FC.input_data[!Ab.RNA.BTM.rows_with_na, ]

Ab.RNA.BTM.FC.input_data = Ab.RNA.BTM.FC.input_data[,!colnames(Ab.RNA.BTM.FC.input_data) %in% c("interferon alpha response (II) (M158.1)", "olfactory receptors (M228)")]

# run SL
CCL3.FC.RNA.BTM.Ab = sl(Ab.RNA.BTM.FC.input_data, target.feature = "D3_D0_FC_CCL3_log_norm", sl.library, cv.fold = 5)
CCL3.FC.RNA.BTM.Ab$model
CCL3.FC.RNA.BTM.Ab$cv

#-----------------------------------------------------------------------------#
# Prediction
#-----------------------------------------------------------------------------#
RNA_BTM_Ab_2022_Day0 = RNA_2022_Day0_norm_top2000 %>%
  left_join(BTM_2022_Day0 %>% 
              mutate(subject_id = as.character(subject_id)), by = "subject_id") %>%
  left_join(Ab_2022_Day0_log_norm %>% 
              mutate(subject_id = as.character(subject_id)), by = "subject_id") %>%
  dplyr::mutate_if(is.numeric, round, digits = 2)

RNA_BTM_Ab_2022_Day0 = RNA_BTM_Ab_2022_Day0[,!colnames(RNA_BTM_Ab_2022_Day0) %in% c("IgG_DT","IgG_FIM2/3","IgG_OVA","IgG_TT")]

setdiff(colnames(Ab.RNA.BTM.FC.input_data), colnames(RNA_BTM_Ab_2022_Day0))
setdiff(colnames(RNA_BTM_Ab_2022_Day0), colnames(Ab.RNA.BTM.FC.input_data))

# use common features in training data
common_cols = intersect(colnames(RNA_BTM_Ab_2022_Day0), 
                        colnames(Ab.RNA.BTM.FC.input_data))

predicting_data = RNA_BTM_Ab_2022_Day0[, common_cols]

# reorder the columns matching with training dataset
predicting_data = predicting_data[, names(Ab.RNA.BTM.FC.input_data[,-2292])]

predicting_data = data.frame(RNA_BTM_Ab_2022_Day0[,c("subject_id", "Gender", "infancy_vac")], 
                             predicting_data)

# Run predict
pred = predict(CCL3.FC.RNA.BTM.Ab$model,  predicting_data[,-c(1:3)], onlySL = TRUE)

# pull out data and rank
res = data.frame(predicting_data[,c(1:3)], CCL3_FC_predict_value = pred$pred, CCL3_FC_Rank = rank(-pred$pred))

res

write.xlsx(res, file = "../PredictionResults/Prediction CCL3 FC.xlsx", col.names = TRUE, row.names = FALSE)
```